export type Ideas = {
  easy: string[];
  medium: string[];
  hard: string[];
};

const ideas: Ideas = {
  easy: [
    "Ask a stranger for the time.",
    "Request a discount at a store, even if you expect the answer to be no.",
    "Compliment someone you don't know.",
    "Invite a friend out for coffee on short notice.",
    "Ask a neighbor if you can borrow an item like a book or a tool.",
    "Request a raise or a more flexible working schedule from your boss.",
    "Ask someone to take a photo of you in a public place.",
    "Offer to help someone with their groceries.",
    "Propose a new idea in a meeting.",
    "Ask for a refund on a purchase, even if it's a small one.",
    "Inquire if you can skip the line somewhere busy, like a coffee shop or restroom.",
    "Ask a coworker for help on a project, even if you think they're busy.",
    "Propose a change in plans to a group of friends.",
    "Request feedback on your work from a colleague.",
    "Ask someone to exchange seats with you in a public transport or at a venue.",
    "Invite a friend to join a hobby you enjoy.",
    "Ask a stranger to recommend a book or a movie.",
    "Request an extension on a deadline.",
    "Ask if you can pet someone’s dog.",
    "Try to return an item without a receipt.",
    "Ask a stranger if they could share their umbrella with you if it's raining.",
    "Offer your services, like tutoring or dog walking, in your neighborhood.",
    "Ask a friend if they can share a recipe.",
    "Inquire about joining a game or activity at the park.",
    "Request a better table at a restaurant.",
    "Ask a librarian for book recommendations on a specific topic.",
    "Request a tour of a place typically not open to the public, like a bakery’s kitchen.",
    "Ask for a taste sample in a store, such as at an ice cream shop or bakery.",
    "Propose a workout challenge to a friend.",
    "Ask for a free upgrade on a service, like a car wash or hotel room.",
    "Invite someone new to a social event.",
    "Ask for the Wi-Fi password in a café.",
    "Request to post a flyer or advertisement in a local store.",
    "Inquire about a promotion or special deal that might not be publicly advertised.",
    "Ask for directions from a stranger, even if you know where you're going.",
    "Propose writing a guest blog post for a blog you follow.",
    "Request to sit in on a class or a meeting that you're interested in.",
    "Ask a stranger for a joke.",
    "Propose a joint venture with a business or a friend.",
    "Ask a restaurant if they can make a dish that isn't on the menu.",
    "Inquire about a scholarship or grant opportunity.",
    "Ask if you can play a song on a public piano.",
    "Propose a barter trade with someone, like services for goods.",
    "Ask someone to share their favorite personal story.",
    "Request to lead a project at work or in a volunteer setting.",
    "Ask for advice on a personal project from an expert.",
    "Propose a new route on a group hike or trip.",
    "Ask someone if you can share their table in a busy café.",
    "Request to shadow a professional in a field of interest.",
    "Ask a store if they can hold an item for you until the end of the day.",
  ],
  medium: [
    "Ask a neighbor if you can host a block party or community event.",
    "Request a personal day off work on short notice.",
    "Ask for a free trial extension for a service you're currently using.",
    "Propose a new project or initiative at work.",
    "Ask a local gym if they can offer a free personal training session.",
    "Inquire at a cafe or restaurant if they would consider featuring your favorite dish.",
    "Request a guest lecture opportunity at a local school or university.",
    "Ask a local bookstore to host a reading or signing event for an aspiring author.",
    "Propose organizing a workshop in your area of expertise at a community center.",
    "Ask a friend if you can borrow their car for a day.",
    "Request permission to access a private or restricted area, like a rooftop or a garden.",
    "Propose a policy change at your workplace.",
    "Ask a professional for a mentorship session.",
    "Request a discount on a subscription service by negotiating directly with the provider.",
    "Inquire at a local theater if you can audition for a role, even without prior experience.",
    "Ask for a free upgrade to first class when checking in at the airport.",
    "Propose an art or craft class at a local library or community center.",
    "Ask a restaurant to create a custom meal for your dietary needs.",
    "Request to collaborate with a local business for a community event.",
    "Ask a famous author for an interview or a written endorsement of your work.",
    "Inquire about hosting a podcast episode with a guest you admire.",
    "Propose a strategic partnership with another company or professional.",
    "Request a critique of your artistic work from an established artist.",
    "Ask a local sports team if you can play in a practice match.",
    "Propose a change to a popular product to a company.",
    "Request a last-minute appointment with a highly booked specialist.",
    "Ask a friend for a significant loan.",
    "Inquire about volunteering in a high-responsibility role at a charity.",
    "Propose a community clean-up initiative to the city council.",
    "Request a backstage tour at a concert or event.",
    "Ask a company if they would consider implementing your software or tool.",
    "Propose a trial run of your services to a potential client.",
    "Request an unscheduled phone call with a busy executive.",
    "Ask a retailer if they would carry a product you are developing.",
    "Inquire about reducing your rent with your landlord.",
    "Propose a research project to a university department.",
    "Ask a museum if you can have a private viewing of an exhibit.",
    "Request to lead a seminar at a professional conference.",
    "Ask for a waiver of a fee or charge that is typically mandatory.",
    "Propose an improvement to a public space in your neighborhood.",
    "Request a professional to write a forward for your book.",
    "Ask a celebrity for a personalized shout-out.",
    "Propose a fundraising event at your workplace.",
    "Request a full refund on a non-refundable booking.",
    "Ask to be featured in a local newspaper or magazine.",
    "Propose a trade of services with a professional without cash exchange.",
    "Request a significant change to your job role or description.",
    "Ask an artist if you can collaborate on a piece.",
    "Propose a sponsorship deal with a company for an event you are organizing.",
    "Request an exclusive interview with someone typically inaccessible.",
  ],
  hard: [
    "Ask a celebrity for an endorsement of your product or project.",
    "Propose a partnership with a major company as a small business owner.",
    "Request a substantial raise or promotion at work.",
    "Ask a popular venue to host your event for free.",
    "Request an investment in your startup from a known investor.",
    "Propose a radical new strategy or business model to your company's executive team.",
    "Ask a best-selling author to co-write a book with you.",
    "Request a favor from someone you've admired but have never spoken to.",
    "Ask for a significant change in your rental lease terms from your landlord.",
    "Propose to organize and lead a major community event with no prior experience.",
    "Request a meeting with a high-ranking government official.",
    "Ask a top-tier university for an honorary degree.",
    "Propose a controversial topic for discussion at a professional conference.",
    "Ask to shadow a CEO of a major corporation for a day.",
    "Request a prime-time interview slot on a major television network.",
    "Propose an unsolicited piece to a major publication as an unknown writer.",
    "Ask a well-known artist to feature in your debut music album.",
    "Request the creation of a new position specifically for you at your company.",
    "Ask a high-profile influencer to promote a cause you care about without compensation.",
    "Propose a new product or service to a company that could fundamentally change their business.",
    "Request a complete redesign of a product from a company to make it more environmentally friendly.",
    "Ask a famous chef to cater a private event for you at cost.",
    "Propose a strategic alliance between your small non-profit and a major international NGO.",
    "Ask for exclusive rights to distribute a popular product in a new market.",
    "Request a scholarship or funding from an institution to study a niche or rare discipline.",
    "Propose a change in law or policy directly to a legislator.",
    "Ask a prominent academic to publicly debate a topic in their field of expertise.",
    "Request a private tour of a highly secured location, like a government building or historical site.",
    "Propose a performance at a high-profile event with minimal prior public performance experience.",
    "Ask a luxury car dealership if you can test drive their most expensive car without intent to buy.",
    "Request the waiver of a large fee or debt from a financial institution.",
    "Propose an art installation in a prestigious gallery as an emerging artist.",
    "Ask a top software company to integrate your small-scale tool into their platform.",
    "Request an endorsement from a professional body or institution without typical qualifications.",
    "Propose an educational reform initiative to a school board as a community member.",
    "Ask a renowned journalist to cover a story about your community project.",
    "Request a collaboration with a tech giant to develop a new technology.",
    "Propose a pilot for a television show to a network as an amateur filmmaker.",
    "Ask a busy world-class professional for monthly mentorship sessions.",
    "Request a lead role in a play or film with no prior leading experience.",
    "Propose a partnership with an elite sports team for a community sports program.",
    "Ask a leading fashion designer to design a piece for you.",
    "Request a modification to a public space for community benefit, like installing a playground.",
    "Propose a business merger or acquisition as a smaller company CEO.",
    "Ask an airline if you can access their VIP lounge without having the required status.",
    "Request a collaboration with a famous musician for a charity concert.",
    "Propose a new scientific research project to a leading research institution.",
    "Ask a luxury hotel if you can hold a high-profile event for free in their banquet hall.",
    "Request an exclusive distribution agreement from a major manufacturer.",
    "Propose a new traffic or urban planning change to a city council.",
  ],
};

export default ideas;
